site_name: .ragfine documentation
nav:
  - Home: index.md
theme:
  name: readthedocs
# plugins:
#   - search
#    mkdocstrings:
#       handlers:
#         python:
#           show_source: false
#           # You can customize options here, like:
#           docstring_style: google  # Optional, use "numpy", "google", or "sphinx"